move_to_pose:
    msg_type: "nekomimi_bot_interfaces/MoveToPose"
    mode: "action"
    value_rules:
        pose_name: {"type": "string", "name": "指定ポーズ"}
        time_allowance: {"type": "time", "name": "時間"}

move_joint:
    msg_type: "nekomimi_bot_interfaces/MoveJoint"
    mode: "action"
    value_rules:
        target_joint_names[2]: {"type": "string", "name": "指定関節名"}
        target_joint_rad[2]: {"type": "deg", "name": "関節角度"}
        time_allowance: {"type": "time", "name": "時間"}

move_wheel_linear:
    msg_type: "nekomimi_bot_interfaces/MoveWheelLinear"
    mode: "action"
    value_rules:
        target_point:
            x: {"type": "float", "name": "前方: "}
            y: {"type": "float", "name": "左へ: "}
        # time_allowance: {"type": "time", "name": "時間"}

move_wheel_rotate:
    msg_type: "nekomimi_bot_interfaces/MoveWheelRotate"
    mode: "action"
    value_rules:
        target_yaw: {"type": "deg", "name": "回転: "}
        # time_allowance: {"type": "time", "name": "時間"}

speech_word:
    msg_type: "nekomimi_bot_interfaces/TextToSpeech"
    mode: "action"
    value_rules:
        text: {"type": "string", "name": "発話ワード: "}