/**/controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    head_position_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    mobile_base_position_controller:
      type: forward_command_controller/ForwardCommandController

    velocity_controller:
      type: forward_command_controller/ForwardCommandController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


/**/head_position_controller:
  ros__parameters:
    joints:
      - head_pan_joint
      - head_tilt_joint

    allow_partial_joints_goal: true
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity


/**/mobile_base_position_controller:
  ros__parameters:
    joints:
      - body_roll_joint

    interface_name: velocity


/**/velocity_controller:
  ros__parameters:
    joints:
      - left_wheel_joint
      - right_wheel_joint

    interface_name: velocity